// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: api.proto

package gprc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcBanking_GetPersonByID_FullMethodName = "/grpc_banking/GetPersonByID"
)

// GrpcBankingClient is the client API for GrpcBanking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcBankingClient interface {
	GetPersonByID(ctx context.Context, in *IncomePersonID, opts ...grpc.CallOption) (*ReplyPerson, error)
}

type grpcBankingClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcBankingClient(cc grpc.ClientConnInterface) GrpcBankingClient {
	return &grpcBankingClient{cc}
}

func (c *grpcBankingClient) GetPersonByID(ctx context.Context, in *IncomePersonID, opts ...grpc.CallOption) (*ReplyPerson, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyPerson)
	err := c.cc.Invoke(ctx, GrpcBanking_GetPersonByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcBankingServer is the server API for GrpcBanking service.
// All implementations must embed UnimplementedGrpcBankingServer
// for forward compatibility.
type GrpcBankingServer interface {
	GetPersonByID(context.Context, *IncomePersonID) (*ReplyPerson, error)
	mustEmbedUnimplementedGrpcBankingServer()
}

// UnimplementedGrpcBankingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcBankingServer struct{}

func (UnimplementedGrpcBankingServer) GetPersonByID(context.Context, *IncomePersonID) (*ReplyPerson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonByID not implemented")
}
func (UnimplementedGrpcBankingServer) mustEmbedUnimplementedGrpcBankingServer() {}
func (UnimplementedGrpcBankingServer) testEmbeddedByValue()                     {}

// UnsafeGrpcBankingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcBankingServer will
// result in compilation errors.
type UnsafeGrpcBankingServer interface {
	mustEmbedUnimplementedGrpcBankingServer()
}

func RegisterGrpcBankingServer(s grpc.ServiceRegistrar, srv GrpcBankingServer) {
	// If the following call pancis, it indicates UnimplementedGrpcBankingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcBanking_ServiceDesc, srv)
}

func _GrpcBanking_GetPersonByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomePersonID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcBankingServer).GetPersonByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcBanking_GetPersonByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcBankingServer).GetPersonByID(ctx, req.(*IncomePersonID))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcBanking_ServiceDesc is the grpc.ServiceDesc for GrpcBanking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcBanking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_banking",
	HandlerType: (*GrpcBankingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersonByID",
			Handler:    _GrpcBanking_GetPersonByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
